### ISSUE TITLE
使用后被拦截了,需要登录

### ISSUE THREAD

**Issue by biuabiu** [yuequan1997/watchdog-spring-boot-starter#1]
ip:port/watchdog.html 访问需要认证啊,我就知道不靠谱

**Comment by FingersKey** [comment]
首先，我非常重视每一位提出Issues的人以及每一个Issues，其次我在示例中也未重现该BUG，目前在多个项目中引用也未出现您所说的问题，示例可以参考https://github.com/yuequan1997/watchdog-spring-boot-starter/tree/master/sample/watchdog-sample   ，麻烦在说不靠谱之前先把您的配置和代码片段都贴一下，谢谢。

**Comment by yuequan1997** [comment]
首先，我非常重视每一位提出Issues的人以及每一个Issues，其次我在示例中也未重现该BUG，目前在多个项目中引用也未出现您所说的问题，示例可以参考https://github.com/yuequan1997/watchdog-spring-boot-starter/tree/master/sample/watchdog-sample ，麻烦在说不靠谱之前先把您的配置和代码片段都贴一下，谢谢。

**Comment by biuabiu** [comment]
[`配置文件`](url
![image](https://user-images.githubusercontent.com/38499411/49076951-26273800-f275-11e8-95df-415153fd86b4.png)
)

**Comment by yuequan1997** [comment]
您在启动类上面添加了`@EnableWatchDog`注解了吗?

**Comment by biuabiu** [comment]
[启动类](url
![image](https://user-images.githubusercontent.com/38499411/49077008-43f49d00-f275-11e8-841a-0fc58e5ab91d.png)
)

**Comment by yuequan1997** [comment]
您有自己对Security的配置吗？

**Comment by biuabiu** [comment]
现在我去掉我刚才加入的一行代码,现在查看管理页面,就不需要输入密码了

**Comment by yuequan1997** [comment]
哪一行?

**Comment by biuabiu** [comment]
我没有并入任何security

**Comment by biuabiu** [comment]
[](url
![image](https://user-images.githubusercontent.com/38499411/49077215-b5345000-f275-11e8-9dae-a1432363cf05.png)
)

**Comment by biuabiu** [comment]
清除cookie 又需要输入密码; [
![image](https://user-images.githubusercontent.com/38499411/49077297-de54e080-f275-11e8-93ee-f306af855d47.png)
](url)

**Comment by yuequan1997** [comment]
方便把你这个项目做一个Demo发我邮箱吗？

**Comment by biuabiu** [comment]
[有gitee链接,按你的spring4All地址加入配置,你可以测](https://gitee.com/axxc/boot-mybatis)

**Comment by biuabiu** [comment]
[](url)ge](https://user-images.gitbusercontent.com/38499411/49077603-a306e180-f276-11e8-9257-36b0af1c505d.png)
](url) 新建也是报错

**Comment by yuequan1997** [comment]
新建报错你执行了`schema.sql`吗？

**Comment by biuabiu** [comment]
[
![image](https://user-images.githubusercontent.com/38499411/49077638-bade6580-f276-11e8-92be-72e3b8a8d840.png)
](url)

**Comment by biuabiu** [comment]
SQL已经执行,

**Comment by biuabiu** [comment]
[
![image](https://user-images.githubusercontent.com/38499411/49077655-d0538f80-f276-11e8-82ab-d4484853fa3f.png)
](url)

**Comment by yuequan1997** [comment]
返回403，那很有可能是你的配置问题。

**Comment by biuabiu** [comment]
我引入依赖,启动类加上注解,按spring4all文章上的配置贴入,全程我没有动我本身的代码

**Comment by yuequan1997** [comment]
我已经下下你的示例代码来了，我看看就知道了

**Comment by biuabiu** [comment]
,我自测加过一行security.basic.enabled=false,如你所说,这并不影响

**Comment by yuequan1997** [comment]
首先`security.basic.enabled=false`这个的含义与这个完全无关

**Comment by biuabiu** [comment]
可以,你可以先引入版本0.7.0-BETA开始测,现在我是依赖到0.8.1了

**Comment by biuabiu** [comment]
你开始测吧,这个demo项目应该是编译不报错的,搞完我下班回家

**Comment by biuabiu** [comment]
同时,我把你的示例代码down下来也看看

**Comment by yuequan1997** [comment]
经我排查，`Watchdog`是从Spring Boot 2.1.x开始的，而您使用的是`1.5.10`，由于版本的差异可能导致配置无效，建议您升级Spring Boot的版本

**Comment by biuabiu** [comment]
排查的那个问题,springboot2.0以上改动太大了

**Comment by yuequan1997** [comment]
那建议您更换依赖呢，我开发`Watchdog`的时候就已经做过了 `1.5.x`和`2.x`的抉择，最后抉择的是`2.x`，如果`1.5.x`的需求多的话，我可以考虑单独开一个支持`1.5.x`的分支

**Comment by yuequan1997** [comment]
首先应该兼容低版本，这个是个伪命题，是相对于时间来的，`Watchdog`是这个月才开发并上线的，所以当时我是认为从`2.1.x`开始是最为合理的，如果说公司的话，我们公司已经全部使用`2.1.x`
